# Generated by Django 5.1.6 on 2025-02-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_pendingchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id_number',
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
