# Generated by Django 5.1.6 on 2025-02-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contact_id_number_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
