# Generated by Django 5.1.6 on 2025-02-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contacts',
        ),
    ]
